# --- 環境設定 (Environment) ---
env:
  backlog_path: "data/backlog_training.json" # 2022年除外
  dev_profiles_path: "configs/dev_profiles_training.yaml" # 2022年除外
  expert_trajectories_path: "data/expert_trajectories.pkl"
  simulation:
    time_step_hours: 8
    max_days: 365

num_developers: 5170 # 全開発者を使用（トレーニングデータの全5,170人）

# --- 特徴量計算の設定 (Features) ---
features:
  recent_activity_window_days: 30
  all_labels: ["bug", "enhancement", "documentation", "question", "help wanted"]
  label_to_skills:
    bug: ["debugging", "analysis"]
    enhancement: ["python", "design"]
    documentation: ["writing"]
    question: ["communication"]
    help wanted: ["collaboration"]

# --- GATモデルのパス (GAT) ---
gat:
  model_path: "data/gnn_model_collaborative.pt" # 学習済みGATモデルのパス
  graph_data_path: "data/graph_collaborative.pt" # 統一されたグラフデータのパス（学習済み）

# --- 逆強化学習の設定 (IRL) ---
irl:
  expert_path: "data/expert_trajectories.pkl"
  output_weights_path: "data/learned_weights_training.npy"
  learning_rate: 0.0005 # 全員分学習のため少し下げる（0.001→0.0005）
  epochs: 300 # 全員分学習のため増加（200→300）
  use_gat: true
  gat_model_path: "data/gnn_model_collaborative.pt" # GATモデルのパス（学習済み）
  gat_graph_path: "data/graph_collaborative.pt" # グラフデータのパス（学習済み）
  # オンライン学習設定
  online_gat_learning: true # オンライン学習を有効化
  gat_update_frequency: 20 # 全員分学習のため頻度を下げる（5→20）
  gat_learning_rate: 0.00005 # 全員分学習のため学習率を下げる（0.0001→0.00005）
  gat_buffer_size: 2000 # バッファサイズ増加（1000→2000）
  gat_time_window_hours: 96 # より長い時間窓（72→96時間）
  # 収束判定設定
  convergence_patience: 100 # 全員分学習のため増加（50→100）
  convergence_threshold: 0.002 # より厳密な収束判定（0.005→0.002）

# --- 強化学習の設定 (RL) ---
rl:
  total_timesteps: 2000000 # 全員分学習のためさらに増加（1000000→2000000）
  learning_rate: 0.0001 # 全員分学習のため学習率を下げる（0.0003→0.0001）
  gamma: 0.99
  gae_lambda: 0.95
  eps_clip: 0.2
  k_epochs: 4
  rollout_len: 1024 # メモリ効率のため減らす（2048→1024）
  output_model_dir: "models/"
