# --- 環境設定 (Environment) ---
env:
  backlog_path: "data/backlog.json"
  dev_profiles_path: "configs/dev_profiles.yaml"
  simulation:
    time_step_hours: 8
    max_days: 365

# --- 特徴量計算の設定 (Features) ---
features:
  recent_activity_window_days: 30

# --- 逆強化学習の設定 (Inverse Reinforcement Learning) ---
irl:
  # ▼▼▼【ここを修正】▼▼▼
  # 読み込むお手本データを、最終成果物である .pkl ファイルに変更します。
  expert_path: "data/expert_trajectories.pkl"
  # ▲▲▲【ここまで修正】▲▲▲

  learning_rate: 0.01
  epochs: 50
  output_weights_path: "reward_weights.npy"
