# --- 環境設定 (Environment) ---
env:
  backlog_path: "data/backlog.json"
  dev_profiles_path: "configs/dev_profiles.yaml"
  simulation:
    time_step_hours: 8
    max_days: 365

num_developers: 10 # 開発者の数

# --- 特徴量計算の設定 (Features) ---
features:
  recent_activity_window_days: 30
  all_labels: ["bug", "enhancement", "documentation", "question", "help wanted"]
  label_to_skills:
    bug: ["debugging", "analysis"]
    enhancement: ["python", "design"]
    documentation: ["writing"]
    question: ["communication"]
    help wanted: ["collaboration"]

# --- GNNモデルのパス (GNN) ---
gnn:
  model_path: "models/gnn_model.pt" # 学習済みGNNモデルのパス
  graph_data_path: "data/graph_data.pt" # グラフデータのパス

# --- 逆強化学習の設定 (IRL) ---
irl:
  expert_path: "data/expert_trajectories.pkl"
  output_weights_path: "data/learned_weights.npy"
  learning_rate: 0.001
  epochs: 100
  use_gnn: true
  gnn_model_path: "models/gnn_model.pt" # GNNモデルのパス
  gnn_graph_data_path: "data/graph_data.pt" # GNNのグラフデータのパス
  gnn_weight : 0.5 # GNNの重み

# --- 強化学習の設定 (RL) ---
rl:
  # ▼▼▼【ここを追加】▼▼▼
  total_timesteps: 500000 # 学習を行う総ステップ数
  # ▲▲▲【ここまで追加】▲▲▲

  learning_rate: 0.0003
  gamma: 0.99
  gae_lambda: 0.95
  eps_clip: 0.2
  k_epochs: 4
  rollout_len: 2048
  output_model_dir: "models/"
