StefanScherer:
  label_affinity: {}
  skills:
  - python
  total_merged_prs: 1
  touched_files: []
aiordache:
  label_affinity: {}
  skills:
  - python
  total_merged_prs: 1
  touched_files: []
ajlai:
  label_affinity: {}
  skills:
  - python
  total_merged_prs: 1
  touched_files: []
amezin:
  label_affinity:
    status/1-design-review: 1.0
  skills:
  - python
  total_merged_prs: 1
  touched_files: []
chibby0ne:
  label_affinity:
    kind/enhancement: 1.0
  skills:
  - python
  total_merged_prs: 1
  touched_files: []
chris-crone:
  label_affinity: {}
  skills:
  - python
  total_merged_prs: 2
  touched_files: []
deathtracktor:
  label_affinity: {}
  skills:
  - python
  total_merged_prs: 1
  touched_files: []
dependabot-preview[bot]:
  label_affinity:
    dependencies: 0.75
    status/4-ready-to-merge: 0.25
  skills:
  - python
  total_merged_prs: 3
  touched_files: []
glance-:
  label_affinity:
    compose-in-a-container: 1.0
  skills:
  - python
  total_merged_prs: 2
  touched_files: []
glours:
  label_affinity: {}
  skills:
  - python
  total_merged_prs: 2
  touched_files: []
guillaumerose:
  label_affinity: {}
  skills:
  - python
  total_merged_prs: 1
  touched_files: []
jcsirot:
  label_affinity: {}
  skills:
  - python
  total_merged_prs: 1
  touched_files: []
lukas9393:
  label_affinity: {}
  skills:
  - python
  total_merged_prs: 1
  touched_files: []
ndeloof:
  label_affinity:
    area/build: 0.3333333333333333
    status/4-ready-to-merge: 0.6666666666666666
  skills:
  - python
  total_merged_prs: 5
  touched_files: []
okor:
  label_affinity: {}
  skills:
  - python
  total_merged_prs: 1
  touched_files: []
rumpl:
  label_affinity:
    dco/no: 1.0
  skills:
  - python
  total_merged_prs: 3
  touched_files: []
sagarafr:
  label_affinity:
    area/secrets: 0.5
    kind/enhancement: 0.5
  skills:
  - python
  total_merged_prs: 1
  touched_files: []
samueljsb:
  label_affinity: {}
  skills:
  - python
  total_merged_prs: 1
  touched_files: []
smamessier:
  label_affinity: {}
  skills:
  - python
  total_merged_prs: 1
  touched_files: []
ulyssessouza:
  label_affinity:
    dco/no: 0.8
    status/4-ready-to-merge: 0.2
  skills:
  - python
  total_merged_prs: 12
  touched_files: []
zelahi:
  label_affinity: {}
  skills:
  - python
  total_merged_prs: 2
  touched_files: []
