EricHripko:
  label_affinity: {}
  skills:
  - python
  total_lines_changed: 293
  total_merged_prs: 2
  touched_files: []
Shikachuu:
  label_affinity: {}
  skills:
  - python
  total_lines_changed: 13
  total_merged_prs: 1
  touched_files: []
aiordache:
  label_affinity: {}
  skills:
  - python
  total_lines_changed: 179
  total_merged_prs: 8
  touched_files: []
albers:
  label_affinity: {}
  skills:
  - python
  total_lines_changed: 8
  total_merged_prs: 1
  touched_files: []
alexrecuenco:
  label_affinity: {}
  skills:
  - python
  total_lines_changed: 735
  total_merged_prs: 1
  touched_files: []
asterite3:
  label_affinity: {}
  skills:
  - python
  total_lines_changed: 40
  total_merged_prs: 1
  touched_files: []
bartier:
  label_affinity: {}
  skills:
  - python
  total_lines_changed: 37
  total_merged_prs: 1
  touched_files: []
chris-crone:
  label_affinity: {}
  skills:
  - python
  total_lines_changed: 32
  total_merged_prs: 1
  touched_files: []
dependabot-preview[bot]:
  label_affinity:
    dependencies: 1.0
  skills:
  - python
  total_lines_changed: 48
  total_merged_prs: 17
  touched_files: []
hartwork:
  label_affinity: {}
  skills:
  - python
  total_lines_changed: 4
  total_merged_prs: 1
  touched_files: []
jarulsamy:
  label_affinity: {}
  skills:
  - python
  total_lines_changed: 175
  total_merged_prs: 1
  touched_files: []
laurazard:
  label_affinity: {}
  skills:
  - python
  total_lines_changed: 97
  total_merged_prs: 1
  touched_files: []
maaarghk:
  label_affinity: {}
  skills:
  - python
  total_lines_changed: 6
  total_merged_prs: 1
  touched_files: []
mat007:
  label_affinity: {}
  skills:
  - python
  total_lines_changed: 4
  total_merged_prs: 1
  touched_files: []
mikesep:
  label_affinity:
    area/cli: 0.3333333333333333
    kind/feature: 0.3333333333333333
    status/2-code-review: 0.3333333333333333
  skills:
  - python
  total_lines_changed: 208
  total_merged_prs: 1
  touched_files: []
ndeloof:
  label_affinity: {}
  skills:
  - python
  total_lines_changed: 9
  total_merged_prs: 2
  touched_files: []
pokutuna:
  label_affinity: {}
  skills:
  - python
  total_lines_changed: 51
  total_merged_prs: 1
  touched_files: []
smola:
  label_affinity: {}
  skills:
  - python
  total_lines_changed: 5
  total_merged_prs: 1
  touched_files: []
svarogg:
  label_affinity: {}
  skills:
  - python
  total_lines_changed: 6
  total_merged_prs: 1
  touched_files: []
thaJeztah:
  label_affinity: {}
  skills:
  - python
  total_lines_changed: 39
  total_merged_prs: 2
  touched_files: []
ulyssessouza:
  label_affinity: {}
  skills:
  - python
  total_lines_changed: 525
  total_merged_prs: 7
  touched_files: []
