# 高速テスト用設定
# 開発・デバッグ用の軽量設定

# === 実験情報 ===
experiment:
  name: "quick_test"
  description: "高速テスト用設定（開発・デバッグ用）"
  seed: 42

# === 時系列データ分割（厳格遵守） ===
temporal_split:
  irl_end_date: "2021-12-31"
  train_start_date: "2022-01-01"
  train_end_date: "2022-12-31"
  test_start_date: "2023-01-01"

# === データパス ===
data:
  irl:
    backlog_path: "data/backlog_irl.json"
    dev_profiles_path: "configs/dev_profiles.yaml"
    expert_trajectories_path: "data/expert_trajectories_bot_excluded.pkl"

# === 環境設定（軽量） ===
env:
  num_developers: 20 # 少数で高速化
  simulation:
    time_step_hours: 4
    max_days: 30

  bot_filtering:
    enabled: true
    patterns: ["[bot]"]

# === IRL設定（高速） ===
irl:
  epochs: 10 # 少ないエポック数
  learning_rate: 0.001
  batch_size: 32
  output_weights_path: "data/learned_weights_test.npy"

  early_stopping:
    patience: 5
    min_improvement: 0.01

# === RL設定（高速） ===
rl:
  total_timesteps: 50000 # 少ないステップ数
  learning_rate: 0.0003

  gamma: 0.99
  rollout_len: 128
  batch_size: 64

  save_freq: 10000
  output_model_dir: "models/quick_test/"

# === 評価設定（軽量） ===
evaluation:
  eval_episodes: 50
  success_threshold: 0.1
  metrics:
    - "top_1_accuracy"
    - "top_3_accuracy"

# === ログ設定 ===
logging:
  level: "INFO"
  tensorboard: false
  log_freq: 1000
