# --- 環境設定 (Environment) ---
env:
  backlog_path: "data/backlog_test_2022.json" # 2022年のみ
  dev_profiles_path: "configs/dev_profiles_test_2022.yaml" # 2022年のみ
  expert_trajectories_path: "data/expert_trajectories.pkl"
  simulation:
    time_step_hours: 8
    max_days: 365

num_developers: 21 # 開発者の数（プロフィールファイルの全開発者を使用）

# --- 特徴量計算の設定 (Features) ---
features:
  recent_activity_window_days: 30
  all_labels: ["bug", "enhancement", "documentation", "question", "help wanted"]
  label_to_skills:
    bug: ["debugging", "analysis"]
    enhancement: ["python", "design"]
    documentation: ["writing"]
    question: ["communication"]
    help wanted: ["collaboration"]

# --- GATモデルのパス (GAT) ---
gat:
  model_path: "data/gat_model_unified.pt" # 学習済みGATモデルのパス
  graph_data_path: "data/graph_train_unified.pt" # 統一されたグラフデータのパス

# --- 逆強化学習の設定 (IRL) ---
irl:
  expert_path: "data/expert_trajectories.pkl"
  output_weights_path: "data/learned_weights.npy"
  learning_rate: 0.001
  epochs: 100
  use_gat: true
  gat_model_path: "data/gat_model_unified.pt" # GATモデルのパス
  gat_graph_path: "data/graph_train_unified.pt" # グラフデータのパス（正しいキー名）
  # オンライン学習設定
  online_gat_learning: true # オンライン学習を有効化
  gat_update_frequency: 10 # 10回のインタラクションごとに更新
  gat_learning_rate: 0.0003 # GATの学習率
  gat_buffer_size: 500 # インタラクションバッファサイズ
  gat_time_window_hours: 48 # 時間窓を拡大（48時間）
  # 収束判定設定
  convergence_patience: 50 # 50エポック改善なしで早期停止
  convergence_threshold: 0.01 # 損失改善の閾値

# --- 強化学習の設定 (RL) ---
rl:
  # ▼▼▼【ここを追加】▼▼▼
  total_timesteps: 500000 # 学習を行う総ステップ数
  # ▲▲▲【ここまで追加】▲▲▲

  learning_rate: 0.0003
  gamma: 0.99
  gae_lambda: 0.95
  eps_clip: 0.2
  k_epochs: 4
  rollout_len: 2048
  output_model_dir: "models/"
